### ISSUE TITLE
update UA Agent

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/DSS#128]
Could we add please a useragent to DSS visits of lib-solr? 

https://dashboard.signalsciences.net/corps/pu_library/sites/poc_site/requests/5d9ad63f0ee43a72747e37c7

**Comment by kevinreiss** [comment]
@kayiwa what do you see from other Blacklight apps? This is a basic implementation using rsolr.

**Comment by kayiwa** [comment]
they have varying versions of Faraday @kevinreiss

**Comment by kevinreiss** [comment]
@kayiwa is this still something we should do?

**Comment by kevinreiss** [comment]
We don't use signal sciences any longer. I don't think this is still relevant.
