### ISSUE TITLE
Landing Page Content

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#15]
Should be an updated version of:

http://dss.princeton.edu/.

**Comment by kevinreiss** [comment]
The blacklight /catalog page should live there but not be aliased to the homepage. Homepage should contain departmental information, guide links and prompts for the catalog.

**Comment by kevinreiss** [comment]
@axamei my thought here is use the high_voltage gem that we've used on other projects to create a static page we can point the rails app root path route to. We can create some helpers that dump out the list of subjects and regions you see on the current page which is something he wants to keep around. The sidebar can contain the boilerplate content that exists there now  that points to all the DSS tutorials and other static content (which we will eventually all move over to Drupal).

**Comment by axamei** [comment]
Sounds good.

**Comment by axamei** [comment]
Are "Find Data by Subject" and "Find Data by Region" the same as "Topic" and "Country" facets? Should we just keep the facets and replace the "Find Data by..." sections for the landing page @kevinreiss?

**Comment by kevinreiss** [comment]
Yes, I think we should pursue that approach. High voltage is probably overkill for this.
