### ISSUE TITLE
Studies marked medium "cd" need access message 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#206]
If a study record is marked "cd" in the medium we should display an access message rather than a link to a folder on the DSS server. The message should be:

```Please go to the Microforms Office - Firestone A Floor and request the study number of the CD-ROM```

**Comment by kevinreiss** [comment]
An example is https://dss.princeton.edu/studies/789

**Comment by carolyncole** [comment]
@kevinreiss the example given does not have medium of cd, not as far as I can tell does any items.  One items that really seems to be a CD has a medium of Server https://dss-staging.princeton.edu/studies/793.json

**Comment by carolyncole** [comment]
Currently on the production server there are 73 items with a Medium set to "CD"  neither of the above ones have that set, so I will assume the site matianer will fix that issue if need be an concentrate on these:`[47, 57, 107, 169, 173, 220, 246, 289, 340, 341, 372, 385, 386, 469, 537, 547, 574, 613, 614, 625, 626, 638, 642, 647, 657, 660, 661, 663, 664, 665, 672, 696, 701, 703, 711, 714, 717, 718, 739, 750, 778, 781, 796, 810, 822, 824, 828, 830, 831, 832, 833, 835, 837, 838, 839, 841, 843, 862, 865, 866, 868, 871, 872, 875, 877, 918, 977, 988, 994, 1021, 1022, 1047, 1277]`

**Comment by kevinreiss** [comment]
I will advise Bobray these are the only ones with this value set.
