### ISSUE TITLE
Add a rake task to add / remove admin users

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/DSS#251]
### Success criteria

- [x] There is a rake task to add admin users that accepts a netid as a parameter.
- [x] The add admin users rake task will create the user if it doesn't exist.
- [x] The add admin users task will set the user's `role` to the string `admin`.
- [x] The add admin users task will do nothing if the netid's user is already an admin
- [x] There is a rake task to remove admin users that accepts a netid as a parameter.
- [x] The remove admin users task will set the user's `role` to an empty string if they are an admin.
- [x] The remove admin users task will do nothing if the user is not an admin.

### Implementation notes

Here is the manual process to make an existing user an admin. You can run this in `rails c`.  Probably the rake task would do similar steps:

```
user = User.find_by_uid(uid)
user.role = 'admin'
user.save
```

**Comment by sandbergja** [comment]
you could also just create the user, rather than searching for them.  Or maybe upsert?

**Comment by sandbergja** [comment]
Also look at `u.attributes`

**Comment by sandbergja** [comment]
The removal rake task should just remove the role, not the whole user.

**Comment by kevinreiss** [comment]
If this works well, we should add this task to the other smaller rails projects with admin users (lockers, repec).
