### ISSUE TITLE
Word wrap cuts off facet values

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/DSS#257]
In this example, the value `Afghanistan` is split into two lines in an odd-looking way:

<img width="261" alt="Afghanista on one line of the facet, the letter n is pushed to the next line" src="https://user-images.githubusercontent.com/7086943/167674981-7530cfb2-99c2-4f13-8f2a-61ef1f72cad9.png">

**Comment by kevinreiss** [comment]
Is this the same as #236?
