### ISSUE TITLE
DSS Site Can't Send Email

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#260]
When trying to use the email feature to send a record to yourself you get a "network error" message in the UI.

**Comment by kevinreiss** [comment]
Check to see if the prod environment is on the "trusted" list for the mail relay.

**Comment by christinach** [comment]
We had a similar issue with 'Cite' in orangelight but I don't know if it is related https://github.com/pulibrary/orangelight/issues/1505

**Comment by carolyncole** [comment]
We think this is an emial to lsupport to see if machine is in poneyexpress lists of trusted senders

**Comment by sandbergja** [comment]
Procedures from pul-the-hard-way: https://github.com/pulibrary/pul-the-hard-way/blob/f54dfdc7ada1ff993a721f6edb4aa1707bb3a3a5/services/smtp-mail-server.md -- it seems like action mailer still needs to be configured for the production environment

**Comment by sandbergja** [comment]
The email form itself can't render.  See: https://app.honeybadger.io/projects/101075/faults/86020705

**Comment by sandbergja** [comment]
closed by #272
