### ISSUE TITLE
NoMethodError: undefined method `new_session_path'

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/DSS#274]
Honeybadger link: https://app.honeybadger.io/projects/101075/faults/86066186

```
  def after_omniauth_failure_path_for(scope)
    new_session_path(scope)
  end
```

This is in the devise gem: gems/devise-4.8.1/app/controllers/devise/omniauth_callbacks_controller

I'm not sure how to recreate it, other than using the link in honeybadger.

**Comment by christinach** [comment]
Closing as it has been resolved and not triggered in honeybadger for a long time.
