### ISSUE TITLE
Purge Saved Searches from user accounts

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#284]
See if any older user accounts have any saved searches that will produce errors when the user logs in. 

Also delete old guest users (the DSS database has gotten extremely large). See https://github.com/pulibrary/orangelight/blob/ae03ac2043056a25d86b7a49e1530a64f9c824c4/app/models/user.rb#L84-L88 for Orangelight code that deals with memory issue when deleting a large number of users.

**Comment by sandbergja** [comment]
All the saved searches have been removed.  The `dss:clean:guest_users` rake task is already set to run daily.
