### ISSUE TITLE
production throws a syntax error

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/DSS#289]
Where: production on dss-prod1 after deploy [2943359c](https://github.com/pulibrary/DSS/compare/a0d6ebcfc30c575fdb06b94224c76ee685ea9c4d...2943359c704510baabd4fc110e0521f8d860c0ad)

The error persists; it is being reported from studies_controller.rb in this header: https://dss.princeton.edu/studynum/79'A=0; the error complains about invalid input syntax when trying to look up FROM "studies" WHERE (studynum = '79''A=0') . 

https://app.honeybadger.io/projects/101075/faults/87691025/01GBDYPN7V7X3PQGJFQPKBZFFX?q=occurred.after%3A%227+days+ago%22

### Notes
studynum is an integer field. The application should ignore any studynum that is not an integer. It should redirect to a 404 page. 

```
app/controllers/studies_controller.rb:22:in `number_lookup'

def number_lookup
  @study = Study.where('studynum = :studynum',  studynum: params[:studynum]).take
  if @study
  redirect_to study_path(@study)
```

**Comment by christinach** [comment]
This is happening again https://app.honeybadger.io/projects/101075/faults/87691025
