### ISSUE TITLE
Revamp Edit Widgets for Country, Region, Subject on Resource

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#31]
Currently done with checkboxes (that don't display) maybe we should convert to something using select2 or another friendly way to wade through the categories.

**Comment by kevinreiss** [comment]
I'm going to add some seed data to the project for Regions.

**Comment by axamei** [comment]
Yes, select2 / chosen would be good replacements for the crazy checkbox list. There's some style rules that are screwing up the checkboxes. I'll fix that in the assets gem.
