### ISSUE TITLE
Change mailer configuration from `example.com`

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/DSS#333]
Record emails from DSS currently have the "from" address of `from@example.com` - these should come from a more real email address, so that they are less likely to be caught in spam filters.

### Implementation notes
- See https://github.com/pulibrary/DSS/blob/862100d56cff2e12b80fc35d27d99a0c32a3ce34/app/mailers/application_mailer.rb#L2

**Comment by maxkadel** [comment]
Questions: 
1. What should the email be?
2. Does it need to be hidden behind an environment variable via ansible vault, or can we put it directly in the repo?

**Comment by kevinreiss** [comment]
We can use: data@princeton.edu as the email sender.
