### ISSUE TITLE
Can't deploy to staging via pulbot or ansible tower

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/DSS#341]
Originally discovered by @kevinreiss following the jammy jellyfish upgrade.

### Expected behavior
I can use pulbot or ansible tower to deploy DSS to staging.

### Actual behavior

The deploys fail with a message about "inappropriate ioctl for device".

- [Pulbot error log](https://gist.github.com/pulbot/b64998862ebce5e2531ec68c65a1f5fa)
- [Ansible tower error log](https://ansible-tower.princeton.edu/#/jobs/playbook/201/output) 

I can deploy locally with `cap staging deploy`.

### Steps to replicate

1. `pulbot deploy dss to staging`

### Impact of this bug

It's not very convenient to deploy code to staging to try it out.

### Implementation notes

I wonder if this is an issue where `appdeploy1` can't SSH into `dss-staging1` to do the deploy?

**Comment by maxkadel** [comment]
Could it be related to this? https://askubuntu.com/questions/1404049/ssh-without-password-does-not-work-after-upgrading-from-18-04-to-22-04

**Comment by bess** [comment]
@sandbergja I think you might be onto something with your ssh question. Just tried doing this manually and got this error: 

```
pulsys@appdeploy1:~$ sudo su - deploy
deploy@appdeploy1:~$ ssh deploy@dss-staging1.princeton.edu
The authenticity of host 'dss-staging1.princeton.edu (128.112.202.244)' can't be established.
ECDSA key fingerprint is SHA256:y+WbY2eLsmAUj3LsEwECIfQGTj82gg/JHG/bMsAiIbA.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'dss-staging1.princeton.edu' (ECDSA) to the list of known hosts.

Load key "/home/deploy/.ssh/id_rsa": invalid format
deploy@dss-staging1.princeton.edu's password:
```

**Comment by christinach** [comment]
see: https://docs.google.com/document/d/14-z3v_vUMLTAVw-g1OlSfqCicQb2BKd9q3RYQqoi4z4/edit

**Comment by kevinreiss** [comment]
Closing will use tower to deploy staging for the future.
