### ISSUE TITLE
Accessibility issues on DSS regions page

### ISSUE THREAD

**Issue by lizgarciao** [pulibrary/DSS#375]
### Steps to recreate
1. Go to https://dss.princeton.edu/regions
2. Log in
3. Visit [this page](https://dss.princeton.edu/regions)
4. click "edit" for one of the rows
5.  click "Update Region".
6. Run axe DevTools on this page.

### URL
https://dss.princeton.edu/regions

### Issues

- [x]  Contrast issue with text "Key Term". [Resolved by PR #410](https://github.com/pulibrary/DSS/pull/410)
- [x]  Button tag needs role attribute https://github.com/pulibrary/DSS/pull/492
- [x]  `"<ul> and <ol> must only directly contain <li>, <script> or <template> elements"` --> This was resolved after updating lux to 4.5.1 [see comment](https://github.com/pulibrary/DSS/issues/375#issuecomment-1783290263) [Resolved by PR #410](https://github.com/pulibrary/DSS/pull/410)

### Severity
Serious

### WCAG Conformance level (A, AA, AAA)
AA

### User impact
Affects users with low vision and users that utilize screen readers.

### Recommended fix
Please see what axe DevTools suggests in order to fix each of these issues.

### Acceptance criteria
- [ ] I can successfully use this feature with Voice Over in Safari.
- [ ] I have checked this feature using one of the following browser extensions and confirmed that it does not add any level A or level AA issues:
    * axe dev tools
    * Lighthouse
    * Wave

### Notes

**Comment by ishasinha1** [comment]
I think #3 is a Lux issue! You need to update lux to v4.5.1.

**Comment by christinach** [comment]
@lizgarciao also update lux to the [latest version v4.5.6](https://github.com/pulibrary/lux/releases/tag/v4.5.6)
