### ISSUE TITLE
Add Select All for Countries on Resource Edit

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/DSS#40]
Gotta add them all!

**Comment by axamei** [comment]
There's an `allowClear` option, but I don't see anything for selecting all options. 

That feature has been requested though and others have created hacks to implement it: https://github.com/select2/select2/issues/195

**Comment by kevinreiss** [comment]
Do you want to give this one a try.

**Comment by kevinreiss** [comment]
Received another request for this feature. Would like a means to apply the tags for "all countries" to a given resource. Right now we have a standard autocomplete widget in the record edit form.![Screen Shot 2023-01-05 at 8.44.00 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/fe7e803e-dbc9-4ad5-92e2-b08109c934a5)![Screen Shot 2023-01-05 at 8.44.00 AM.png](https://images.zenhubusercontent.com/5cba088397df763a9090ce23/799920ec-aa21-4aba-b204-e505dc9d55a8)

Perhaps we could workout a toggle option on the "New" record form. Where the user choses between applying all countries or seeing the standard form element to apply a small number of country options.
