### ISSUE TITLE
point dss to the new solrd cluster

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/DSS#404]
- [x] have the dss-staging vm point to the new solr-d cluster https://github.com/pulibrary/DSS/pull/405
- [x] Run the index rake task to populate the new collection: ```bundle exec rake dss:solr:index```

**Comment by kevinreiss** [comment]
Creating a collection called dss-staging1 with an alias "dss-staging" was needed in the solr set-up for the re-index task to run successfully per @sandbergja, @christinach and @kayiwa.
