### ISSUE TITLE
Login button giving 500 error

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/DSS#446]
### Expected behavior
Can log in to the application

### Actual behavior
Get a 500 error

### Steps to replicate
1. Go to https://dss.princeton.edu/catalog
2. Open network tools
3. Click "login"

### Impact of this bug
Staff will not be able to log in to create or edit data.

### Honeybadger link and code snippet, if applicable
[Honeybadger error](https://app.honeybadger.io/projects/101075/faults/108724004)

```
NoMethodError: undefined method `new_session_path' for <Users::OmniauthCallbacksController> new_session_path(scope) ^^^^^^^^^^^^^^^^ Did you mean? new_region_path
def after_omniauth_failure_path_for(scope)
  new_session_path(scope)
end
```

**Comment by kevinreiss** [comment]
Just noting that this happens in both staging and prod and from both the login link on the site's header and from individual study pages with CAS protected file content: https://dss-staging.princeton.edu/studies/578/ and https://dss.princeton.edu/studies/578.
