### ISSUE TITLE
Set up DSS locally

### ISSUE THREAD

**Issue by christinach** [pulibrary/DSS#468]
Go through the READme and set up DSS locally.

1. [Local Development Basic Setup](https://github.com/pulibrary/DSS?tab=readme-ov-file#local-development-basic-setup)
2. [Make yourself an admin](https://github.com/pulibrary/DSS?tab=readme-ov-file#making-yourself-an-admin-user)
3. [Run the tests](https://github.com/pulibrary/DSS?tab=readme-ov-file#running-the-tests)

**Comment by vh8154** [comment]
Done!
